[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

[build]
rustflags = [
  # GNU LD
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlinkall.x",

  # LLD
  # "-C", "linker=rust-lld",
  # "-C", "link-arg=-Tlinkall.x",
]
target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core", "alloc"]


#[build]
#target = "xtensa-esp32-espidf"
#
#[target.xtensa-esp32-espidf]
#linker = "ldproxy"
## runner = "espflash --monitor" # Select this runner for espflash v1.x.x
#runner = "espflash flash --monitor" # Select this runner for espflash v2.x.x
#rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

#[unstable]
#build-std = ["std", "panic_abort"]


#[env]
#MCU="esp32"
## Note: this variable is not used by the pio builder (`cargo build --features pio`)
#ESP_IDF_VERSION = "v5.1.1"
#ESP_IDF_GLOBAL_INSTALL = { value = "y" }

